#!/bin/bash

#
# enable-wazuh-archives (part of the Blue Wolf Ninja Wazuh Windows Logtest helper suite
# by Kevin Branch (@BlueWolfNinja)
# https://bluewolfninja.com
# 
# Authoritatively available from:
# https://github.com/BlueWolfNinja/wazuh-resources
#
# Explained in this blog article
# https://bluewolfninja.com/simulating-wazuh-analysis-of-sample-windows-events
#
# This script extracts sets the <logall_json> value in ossec.conf on Wazuh manager to yes and then restarts the wazuh-manager service, to make the service
# start writing unadbridged log events to archives.json.
#

sudo sed -i 's/   <logall_json>.*/   <logall_json>yes<\/logall_json>/' /var/ossec/etc/ossec.conf
sudo systemctl restart wazuh-manager
