#!/bin/bash

#
# wazuh-logtest-eventchannel (part of the Blue Wolf Ninja Wazuh Windows Logtest helper suite)
# by Kevin Branch (@BlueWolfNinja)
# https://bluewolfninja.com
# 
# Authoritatively available from:
# https://github.com/BlueWolfNinja/wazuh-resources
#
# Explained in this blog article
# https://bluewolfninja.com/simulating-wazuh-analysis-of-sample-windows-events
#
# At this time, Wazuh's native logtest facility has no direct support for testing Windows event samples.
# This wrapper of the wazuh-logtest-legacy CLI program can be fed unescaped JSON full_log field samples of Windows events from a Wazuh manager's archives.json file.
# One way to acquire such samples is to use the extract_windows_full_log_samples companion script to wazuh-logtest-eventchannel, available from the same Github repo.
#

sed 's/<rule_dir>ruleset\/rules<\/rule_dir>/<rule_dir>ruleset\/rules-logtest<\/rule_dir>/' /var/ossec/etc/ossec.conf > /var/ossec/etc/ossec-logtest.conf
mkdir /var/ossec/ruleset/rules-logtest 2> /dev/null
rsync -pog /var/ossec/ruleset/rules/* /var/ossec/ruleset/rules-logtest/
sed -i '/<rule id="60000" level="0">/,+7 d' /var/ossec/ruleset/rules-logtest/0575-win-base_rules.xml
sed -i 's/<group name="windows,">/<group name="windows,">\n\n  <rule id="60000" level="0">\n    <decoded_as>json<\/decoded_as>\n    <field name="win.system.providerName">\\.+<\/field>\n    <description>Group of windows rules<\/description>\n  <\/rule>/' /var/ossec/ruleset/rules-logtest/0575-win-base_rules.xml
/var/ossec/bin/wazuh-logtest-legacy -c /var/ossec/etc/ossec-logtest.conf $1 $2 $3
